
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btsupport.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0c3VwcG9ydCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzQzNDk4NTE5LCJleHAiOjIwNTkwNzQ1MTl9.wBqGGnXdF_T0jZSfnQkCQtlEbGdTS2JYjRCe42_NeLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
