// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muknputruqyjfwikztyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11a25wdXRydXF5amZ3aWt6dHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTg1MTksImV4cCI6MjA1OTA3NDUxOX0.F6sQ6kCRlWMtVMs6fsrlAHxQ7GZ9Az2Y7ljr-jYvx3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);